[build]
  command = "go build -o functions/myfunction ./..."
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/midoriyaizukudeku/go"
  GO111MODULE = "on"
